tom_publications/urls.py
from django.urls import path

from tom_publications.views import LatexTableView

app_name = 'tom_publications'

urlpatterns = [
    path('latex/create/', LatexTableView.as_view(), name='create-latex'),
]

tom_publications_base/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('publications/', include('tom_publications.urls', namespace='publications')),
    path('admin/', admin.site.urls),
]

tom_publications/models.py
from django.db import models


class LatexConfiguration(models.Model):
    fields = models.TextField(blank=False, default='')
    model_name = models.CharField(blank=False, default='', max_length=120)
    template = models.CharField(blank=False, default='', max_length=200)

tom_publications/forms.py
from django import forms


class LatexTableForm(forms.Form):

    model_pk = forms.IntegerField(
        widget=forms.HiddenInput(),
        required=True
    )
    model_name = forms.CharField(
        widget=forms.HiddenInput(),
        required=True
    )
    template = forms.CharField(widget=forms.HiddenInput(), required=False)

tom_publications/views.py
from django.apps import apps
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView

from tom_publications.latex import get_latex_processor
from tom_publications.models import LatexConfiguration


class LatexTableView(LoginRequiredMixin, TemplateView):
    template_name = 'tom_publications/latex_table.html'

    def get(self, request, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        model_name = request.GET.get('model_name')
        obj = None
        if not model_name:
            raise Exception
        else:
            model = apps.get_model(model_name)
            obj = model.objects.get(pk=request.GET.get('model_pk'))

        processor = get_latex_processor(model_name.split('.')[1])

        latex = []
        if 'create-latex' in request.GET or 'save-latex' in request.GET:
            latex_form = processor.get_form(request.GET)
            if latex_form.is_valid():
                latex_form.clean()

                latex = processor.generate_latex(
                    latex_form.cleaned_data
                )
                if request.GET.get('save-latex'):
                    config = LatexConfiguration(
                        fields=','.join(latex_form.cleaned_data['field_list']),
                        model_name=latex_form.cleaned_data['model_name']
                    )
                    config.save()
        else:
            latex_form = processor.get_form(initial=request.GET)

        context['object'] = obj
        context['latex_form'] = latex_form
        context['latex'] = latex

        return self.render_to_response(context)

tom_publications/templates/tom_publications/latex_table.html
{% extends 'tom_common/base.html' %}
{% load bootstrap4 crispy_forms_tags %}
{% bootstrap_javascript jquery='True' %}
{% block title %}Target {{ object.name }}{% endblock %}
{% block extra_javascript %}
<script>
  function copyLatex() {
    latex = document.getElementById("copy-latex");
    latex.select();
    document.execCommand("copy");
  }
</script>
{% endblock %}
{% block content %}
<div class="row">
  <div id="latex-form" class="col-md-12">
    <h3>Generate latex table for {{ object.name }}</h3>
    <form method="GET" action="{% url 'tom_publications:create-latex' %}" class="form">
      {% csrf_token %}
      {% crispy latex_form %}
    </form>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    {% if latex %}
      <textarea type="text" rows="4" class="form-control" id="copy-latex">{{ latex }}</textarea>
    {% endif %}
  </div>
  <button class="btn btn-outline-primary" onclick="copyLatex()">Copy to clipboard</button>
</div>
{% endblock %}

tom_publications/templates/tom_publications/partials/latex_button.html
<a href="{% url 'tom_publications:create-latex' %}?model_name={{ model_name }}&model_pk={{ model_pk }}" class="btn  btn-outline-primary">Generate Latex</a>